bump dino_park_gate 0.8.1->0.8.2
mozilla-iam/dino-park-packs pull request #21
Opened 2022-02-28 20:01 UTC by floatingatoll

To deploy the issue identified in https://github.com/mozilla-iam/dino-park-gate/issues/7, we need to bump the version number here as well. The associated branch/version are prepared in the repository.

2022-03-14 14:03 UTC, fiji-flo requested changes
Sorry for the delay. I'm still swamped with MDN work. Just to unblock you. This looks okay but you'll need to update the `Cargo.lock` file. Just run a `cargo build` locally.

https://github.com/mozilla-iam/dino-park-packs/runs/5365275676?check_suite_focus=true#step:7:294

2022-03-15 14:51 UTC, fiji-flo approved these changes
That should work

2022-05-02 15:16 UTC, bkochendorfer commented
This looks good, since I am already here should I take this out for you @floatingatoll ?

2022-05-02 15:37 UTC, floatingatoll commented
Sure, let's give it a try. Ping me when it's live.

2022-05-02 16:03 UTC, merged